CREATE TABLE arichannelspostreply (
    id    integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    channel_id varchar(50) NOT NULL,
    name  varchar(50) NOT NULL,
    state varchar(30) NOT NULL,
    protocol_id varchar(50) NOT NULL,
    caller_name varchar(30),
    caller_number varchar(30),
    connected_name varchar(20),
    connected_number varchar(20),
    accountcode varchar(30),
    dialplan_context varchar(30),
    dialplan_exten varchar(10),
    dialplan_priority integer,
    dialplan_app_name varchar(30),
    dialplan_app_data varchar(30),
    creationtime varchar(30),
    language varchar(5)
);

CREATE TABLE test_arichannelspostreply (
                                      channel_id varchar(50) NOT NULL,
                                      name  varchar(50) NOT NULL,
                                      state varchar(30) NOT NULL,
                                      protocol_id varchar(50) NOT NULL,
                                      caller_name varchar(30),
                                      caller_number varchar(30),
                                      connected_name varchar(20),
                                      connected_number varchar(20),
                                      accountcode varchar(30),
                                      dialplan_context varchar(30),
                                      dialplan_exten varchar(10),
                                      dialplan_priority integer,
                                      dialplan_app_name varchar(30),
                                      dialplan_app_data varchar(30),
                                      creationtime varchar(30),
                                      language varchar(5)
);